name: Bash CLI Actions
on:
  push:
    paths:
      - 'bash-cli/**'
jobs:
  build-test-style:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./bash-cli
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
     
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Execute Gradle ktlintCheck
      run: ./gradlew ktlintCheck
